name: tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: [7.3, 7.4, '8.0', 8.1, 8.2]
        laravel: [8, 9, 10]
        exclude:
          - php: 7.3
            laravel: 9
          - php: 7.3
            laravel: 10
          - php: 7.4
            laravel: 9
          - php: 7.4
            laravel: 10
          - php: '8.0'
            laravel: 10

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer require "illuminate/contracts=^${{ matrix.laravel }}" --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
